### ISSUE TITLE
defmethod -- naming

### ISSUE THREAD

**Issue by Fuco1** [kurisuwhyte/emacs-multi#4]
As you've mentioned yesterday, the `defgeneric` and `defmethod` come from CL. I've checked the emacs sources (being the suspicious kind I am) and there already is a `defmethod` defined in emacs's `emacs-lisp/eieio.el`. So, by loading your package _after_ someone loaded eieio would shadow that method (or the other way 'round).

This basically means using this package in other packages is not safe. This is caused by the stupid issue that emacs doesn't have namespaces.

I would therefore advise you to change the name to something else, probably just adding a prefix. Any good ideas?

**Comment by kurisuwhyte** [comment]
Ah, yes, that would be a huge problem :(

I'm thinking about `defmulti`, `defmulti-method` and `defmulti-method-fallback`, instead of `defmulti`, `defmethod` and `defmethod-fallback`, respectively, which should fix the problem, unless someone out there has already named one of their functions `defmulti` ;)

But yeah, having Clojure-style namespaces in Emacs would be awesome. No conflicts and less verbosity ♥

PS.: Or perhaps just `defmulti-fallback` rather than `defmulti-method-fallback`. Not as clear, but less verbose(?)

**Comment by Fuco1** [comment]
Yes, that sounds good. The usual practice (or rather mispractice, instead of fixing the namespaces) is to add the prefixes to all the functions. Which in your case can very well be `defmulti` itself.

`defmulti`, `defmulti-method` and `defmulti-fallback` sounds good.

Also another "stylistic" thing, the naming `(multi)/-` is also a bit "unstandard". Usually, in emacs either `/` or `--` is used for internals to separate the "namespace prefix" (often `/` is also used for public methods).

**Comment by kurisuwhyte** [comment]
Ah, I'm a clojurian so I'm used to `-private` naming. I also think `/-` screams more "hey, I'm supposed to be private" than `--`
